import { Transaction, RevenueItem, CostItem, MonthlyData } from '@/types'

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    date: new Date('2023-10-12'),
    description: 'Fattura n. 45 - Progetto Web',
    details: 'Cliente: Acme Corp',
    category: 'Vendite',
    account: 'Intesa Business',
    amount: 2400,
    status: 'Confermato',
    type: 'entrata',
  },
  {
    id: '2',
    date: new Date('2023-10-11'),
    description: 'Affitto Sede Centrale',
    details: 'Canone mensile Ottobre',
    category: 'Immobili',
    account: 'Revolut Business',
    amount: -1200,
    status: 'Confermato',
    type: 'uscita',
  },
  {
    id: '3',
    date: new Date('2023-10-10'),
    description: 'Pagamento AWS - Hosting',
    details: 'ID: 2394023-AMZ',
    category: 'Tecnologia',
    account: 'Revolut Business',
    amount: -156.40,
    status: 'In sospeso',
    type: 'uscita',
  },
  {
    id: '4',
    date: new Date('2023-10-09'),
    description: 'Rimborso Spese Trasferta',
    details: 'Nota spese: G. Bianchi',
    category: 'Personale',
    account: 'Cassa Contanti',
    amount: -45,
    status: 'Confermato',
    type: 'uscita',
  },
  {
    id: '5',
    date: new Date('2023-10-08'),
    description: 'Incasso Consulenza Strategy',
    details: 'Cliente: Global Ltd',
    category: 'Consulenza',
    account: 'Intesa Business',
    amount: 5000,
    status: 'Confermato',
    type: 'entrata',
  },
  {
    id: '6',
    date: new Date('2023-10-07'),
    description: 'Fattura n. 44 - Sviluppo App',
    details: 'Cliente: Tech Solutions',
    category: 'Vendite',
    account: 'Intesa Business',
    amount: 3500,
    status: 'Confermato',
    type: 'entrata',
  },
  {
    id: '7',
    date: new Date('2023-10-06'),
    description: 'Stipendio Personale',
    details: 'Ottobre 2023',
    category: 'Personale',
    account: 'Intesa Business',
    amount: -4500,
    status: 'Confermato',
    type: 'uscita',
  },
  {
    id: '8',
    date: new Date('2023-10-05'),
    description: 'Campagna Marketing Digitale',
    details: 'Google Ads - Ottobre',
    category: 'Marketing',
    account: 'Revolut Business',
    amount: -1500,
    status: 'Confermato',
    type: 'uscita',
  },
]

export const mockRevenueItems: RevenueItem[] = [
  {
    id: '1',
    name: 'Vendita Prodotti',
    amount: 84000,
    percentage: 67,
  },
  {
    id: '2',
    name: 'Consulenza Tecniche',
    amount: 31400,
    percentage: 25,
  },
  {
    id: '3',
    name: 'Licenze Software',
    amount: 10000,
    percentage: 8,
  },
]

export const mockCostItems: CostItem[] = [
  {
    id: '1',
    name: 'Personale e Collaboratori',
    amount: 45000,
    percentage: 55,
  },
  {
    id: '2',
    name: 'Affitto e Utenze',
    amount: 12300,
    percentage: 15,
  },
  {
    id: '3',
    name: 'Marketing e Pubblicità',
    amount: 15000,
    percentage: 18,
  },
  {
    id: '4',
    name: 'Oneri Diversi',
    amount: 10000,
    percentage: 12,
  },
]

export const mockMonthlyData: MonthlyData[] = [
  { month: 'MAG', revenue: 98000, costs: 75000, profit: 23000 },
  { month: 'GIU', revenue: 105000, costs: 78000, profit: 27000 },
  { month: 'LUG', revenue: 112000, costs: 80000, profit: 32000 },
  { month: 'AGO', revenue: 118000, costs: 82000, profit: 36000 },
  { month: 'SET', revenue: 122000, costs: 81000, profit: 41000 },
  { month: 'OTT', revenue: 125400, costs: 82300, profit: 43100 },
]
